<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matt Lawrence">
<meta name="dcterms.date" content="2023-09-14">

<title>SOCI 385, Week One, Class Two</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="notebook_01_02_ml_files/libs/clipboard/clipboard.min.js"></script>
<script src="notebook_01_02_ml_files/libs/quarto-html/quarto.js"></script>
<script src="notebook_01_02_ml_files/libs/quarto-html/popper.min.js"></script>
<script src="notebook_01_02_ml_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="notebook_01_02_ml_files/libs/quarto-html/anchor.min.js"></script>
<link href="notebook_01_02_ml_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="notebook_01_02_ml_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="notebook_01_02_ml_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="notebook_01_02_ml_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="notebook_01_02_ml_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="notebook_01_02_ml_files/libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<link href="notebook_01_02_ml_files/libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="notebook_01_02_ml_files/libs/datatables-binding-0.29/datatables.js"></script>
<script src="notebook_01_02_ml_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="notebook_01_02_ml_files/libs/dt-core-1.13.4/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="notebook_01_02_ml_files/libs/dt-core-1.13.4/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="notebook_01_02_ml_files/libs/dt-core-1.13.4/js/jquery.dataTables.min.js"></script>
<link href="notebook_01_02_ml_files/libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="notebook_01_02_ml_files/libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SOCI 385, Week One, Class Two</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Matt Lawrence </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 14, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting Started</h2>
<p>To begin, copy all the text on this screen. Then open RStudio, and in the “File” menu select “New File” then “Quarto.” Include your name in the “Author” box, add a title like “SOCI 385, Week One, Class Two”, select “HTML” as the output format, and click Create. A default Quarto file will open. Delete all the text in the default file below the header (everything after line 5) and paste in the text you copied to your clipboard. Make sure that “Quarto” is selected in the file type drop down menu in the bottom right corner of this pane. Save this file where you want to save files for this class.</p>
</section>
<section id="welcome-to-r-studio" class="level2">
<h2 class="anchored" data-anchor-id="welcome-to-r-studio">Welcome to R Studio!</h2>
<p>Let’s examine how to navigate this window before we begin.</p>
<ul>
<li>The upper left pane is the <em>text editor</em> where you keep all of your commands.</li>
<li>The lower left pane is the <em>console</em> where the commands will be executed.</li>
<li>The upper right pane’s <code>Environment</code> window will show the data that you load.</li>
<li>The lower right pane will show previews of your R Markdown documents, plots, help documents, packages, and other features.</li>
</ul>
<p>This file is a Quarto document that allows you to integrate text, R code, and R output into a single document. This is the recommended file type for our course, but you may want to use other file types in the future. All the possible file types are found when you click File&gt;New File. For our purposes - and for producing transparent and reproducible research - the advantage of a Quarto document is that you can easily include text, notes, and comments that are not code (like this paragraph).</p>
<p>How does R know what is code and what is regular text? In a Quarto document, code goes in a fenced code block. To open the fence, type three backticks and an r in curly brackets on a single line; to close the fence, type three backticks on a single line like this:</p>
<p>Everything between those fences will be run as code (unless it is preceded by a hashtag).</p>
<p><strong><em>Want a shortcut? On a mac, Command-Option-I will open a blank code block. For Windows, use Control-Alt-I.</em></strong></p>
<p>Let’s start by using R as a basic calculator. We’ll add up a couple numbers to get to our course number (385). Since even the following calculation is considered code we need to place it within a code block.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="dv">300</span> <span class="sc">+</span> <span class="dv">85</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 385</code></pre>
</div>
</div>
<p>To run this line of code, click the green arrow on the far right side of the first line of the code block.</p>
<p>After the opening fence, you can add options with the <code>#|</code> tag. One helpful option would be a label of what the code in that chunk does. Those short descriptive labels are collected as bookmarks in the drop down menu on the bottom of this pane and can help you find pieces of your file. <strong><em>Note that multiple chunks cannot have the same label If they do, the file will not knit.</em></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="dv">300</span> <span class="sc">+</span> <span class="dv">85</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 385</code></pre>
</div>
</div>
<p>For subtraction, use a -; for multiplication, use a *; for division, use a /.</p>
<p>What is 770 divided by 2?</p>
<section id="replace-this-line-with-your-code" class="level3">
<h3 class="anchored" data-anchor-id="replace-this-line-with-your-code">REPLACE THIS LINE WITH YOUR CODE</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="dv">770</span> <span class="sc">/</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 385</code></pre>
</div>
</div>
<p>Our course number could be helpful to save so we do not have to calculate it each time we want to reference it. We save a value by creating an object. The syntax for doing so is to name our object first, then use the symbol “&lt;-” to say what value our object takes. Let’s call our new object <code>coursenumber</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>coursenumber <span class="ot">&lt;-</span> <span class="dv">770</span> <span class="sc">/</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Run this line of code. In the top right quadrant, we should see a new value saved. That’s promising, but there’s no output below the code chunk! That’s because we have to separately recall the object for it to be displayed. The only line of code we need to do so is our object name:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>coursenumber</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 385</code></pre>
</div>
</div>
<p>Note that case matters in R code. See how by replacing the <code>c</code> in the previous chunk with a capital <code>C</code>.</p>
<p>We can now use the object we created in other calculations by referring to it by name:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>coursenumber <span class="sc">-</span> <span class="dv">145</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 240</code></pre>
</div>
</div>
<p>Objects can take numerical or character values. The difference is that if we are using text we have to enclose the value in quotation marks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>coursename <span class="ot">&lt;-</span> <span class="st">"Social Statistics"</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>coursename</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Social Statistics"</code></pre>
</div>
</div>
<p>We can now reference these saved objects in our code as well as our text. To use <em>inline code</em>, wrap the code in single backticks with a preceding r:</p>
<blockquote class="blockquote">
<p>This class is called Social Statistics and it is SOCI 385.</p>
</blockquote>
<p>The printed document will replace <code>coursename</code> and <code>coursenumber</code> with their saved values.</p>
</section>
</section>
<section id="introducing-r-markdown" class="level2">
<h2 class="anchored" data-anchor-id="introducing-r-markdown">Introducing R Markdown</h2>
<p>We will be using Quarto documents with R Markdown to write and run our code. R Markdown is a plain text-based form of writing with lots of neat tricks. For example, look at the heading for this paragraph. The two hashtags are how we start a new section in R Markdown. If we used one hashtag, the section heading would be bigger in the output. If we used three (or four) hashtags, the section headings would be smaller (or even smaller) in the output, which would be helpful if you have lots of sub- (or sub-sub-) headings</p>
<p>There’s an R Markdown cheat sheet in the pages folder on Canvas that has much more info on how to use R Markdown. Here are a few first day features to get you started:</p>
<p>Wrapping a word in <code>single backticks</code> will highlight it when you print.</p>
<p><em>Wrapping text in one asterisk will italicize it when you print.</em></p>
<p><strong>Wrapping text in two asterisks will bold it when you print.</strong></p>
<p><strong><em>Wrapping text in three asterisks will bold and italicize it when you print.</em></strong></p>
<p>And three (or more) dashes on a single line will create a horizontal rule:</p>
<hr>
<div style="page-break-after: always;"></div>
</section>
<section id="getting-started-with-r" class="level2">
<h2 class="anchored" data-anchor-id="getting-started-with-r">Getting Started With R</h2>
<p>Today we will learn one way to import data into R and how to get simple summaries of different types of variables.</p>
<p>We will use the <code>hurricanes</code> dataset to explore types of variables. This dataset is provided online by Jung et al as a supplement to their 2014 paper. To find this archival dataset and the datasets for their experiments, click <a href="http://www.pnas.org/content/suppl/2014/05/30/1402786111.DCSupplemental/pnas.1402786111.sd01.xlsx">here.</a></p>
<p>First, we need to install a package. Packages are additional functions that supplement base R. We will use the <code>tidyverse</code> package extensively this semester.</p>
<p>Here’s the code to install the package. You only have to install the package once on any computer you use. Once your computer has the package installed, you can load the package with the <code>library()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("tidyverse")</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<p>Now that the package is installed, you can put a hashtag in front of the <code>install.packages()</code> line so it does not run again.</p>
<p>Next we’ll get the data using the <code>read.csv()</code> function to import a “comma separated value” file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>hurricanes <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mjclawrence/soci385_f23/main/data/hurricanes.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plot" class="level2">
<h2 class="anchored" data-anchor-id="plot">Plot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>hurricanes <span class="sc">|&gt;</span>  <span class="fu">group_by</span>(male_female) <span class="sc">|&gt;</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">summarise</span>(<span class="at">deaths_mean =</span> <span class="fu">round</span>(<span class="fu">mean</span>(deaths),<span class="dv">2</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> male_female, <span class="at">y =</span> deaths_mean, <span class="at">fill =</span> male_female)) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span> </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> deaths_mean), <span class="at">size =</span> <span class="dv">6</span>, <span class="at">vjust =</span> <span class="dv">0</span>) <span class="sc">+</span> </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Mean Number of Deaths"</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Mean Number of Deaths by Gender of Hurricane Name"</span>) <span class="sc">+</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_hc</span>() <span class="sc">+</span> <span class="fu">scale_fill_economist</span>(<span class="at">name =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">25</span>)) <span class="sc">+</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">18</span>),</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">18</span>),</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)) <span class="sc">+</span> <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="notebook_01_02_ml_files/figure-html/plot%20example-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>If you imported the file correctly, you should now see the data frame loaded and saved with the object name you created in the <code>environment</code> panel in the top right quadrant of R Studio. There should be 92 observations of 7 variables in the data frame named hurricanes.</p>
<p>Click the white arrow to the left of the object name to see all the variables (year, name, etc.). Click the spreadsheet icon on the far right side of the data name row to open the full data frame. Note that the <em>variables</em> are in the columns and the <em>values</em> are in the rows, with each row representing a separate <em>observation</em> or <em>case</em>.</p>
<p>For a dataframe with only a few variables like this one, you can also just recall the name of the dataframe to see the content:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>hurricanes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   year      name   masfem gender_mf male_female category deaths
1  1950      easy  6.77778         1      female        3      2
2  1950      king  1.38889         0        male        3      4
3  1952      able  3.83333         0        male        1      3
4  1953   barbara  9.83333         1      female        1      1
5  1953  florence  8.33333         1      female        1      0
6  1954     carol  8.11111         1      female        3     60
7  1954      edna  8.55556         1      female        3     20
8  1954     hazel  9.44444         1      female        4     20
9  1955    connie  8.50000         1      female        3      0
10 1955     diane  9.88889         1      female        1    200
11 1955      ione  5.94444         0        male        3      7
12 1956    flossy  7.00000         1      female        2     15
13 1958    helene  9.88889         1      female        3      1
14 1959     debra  9.88889         1      female        1      0
15 1959    gracie  9.77778         1      female        3     22
16 1960     donna  9.27778         1      female        4     50
17 1960     ethel  8.72222         1      female        1      0
18 1961     carla  9.50000         1      female        4     46
19 1963     cindy  9.94444         1      female        1      3
20 1964      cleo  7.94444         1      female        2      3
21 1964      dora  9.33333         1      female        2      5
22 1964     hilda  8.83333         1      female        3     37
23 1964    isbell  9.44444         1      female        2      3
24 1965     betsy  8.33333         1      female        3     75
25 1966      alma  8.77778         1      female        2      6
26 1966      inez  8.27778         1      female        1      3
27 1967    beulah  7.27778         1      female        3     15
28 1968    gladys  8.94444         1      female        2      3
29 1969   camille  9.05556         1      female        5    256
30 1970     celia  9.44444         1      female        3     22
31 1971     edith  8.50000         1      female        2      0
32 1971      fern  7.38889         1      female        1      2
33 1971    ginger 10.00000         1      female        1      0
34 1972     agnes  8.66667         1      female        1    117
35 1974    carmen  8.72222         1      female        3      1
36 1975    eloise  8.94444         1      female        3     21
37 1976     belle 10.44445         1      female        1      5
38 1977      babe  6.88889         1      female        1      0
39 1979       bob  1.66667         0        male        1      1
40 1979     david  1.72222         0        male        2     15
41 1979  frederic  2.50000         0        male        3      5
42 1980     allen  2.66667         0        male        3      2
43 1983    alicia  9.83333         1      female        3     21
44 1984     diana  9.94444         1      female        2      3
45 1985       bob  1.66667         0        male        1      0
46 1985     danny  2.22222         0        male        1      1
47 1985     elena  9.72222         1      female        3      4
48 1985    gloria  9.50000         1      female        3      8
49 1985      juan  1.94444         0        male        1     12
50 1985      kate  9.66667         1      female        2      5
51 1986    bonnie  9.38889         1      female        1      3
52 1986   charley  2.88889         0        male        1      5
53 1987     floyd  1.83333         0        male        1      0
54 1988  florence  8.33333         1      female        1      1
55 1989   chantal  9.05556         1      female        1     13
56 1989      hugo  2.88889         0        male        4     21
57 1989     jerry  2.33333         0        male        1      3
58 1991       bob  1.66667         0        male        2     15
59 1992    andrew  2.22222         0        male        5     62
60 1993     emily  9.83333         1      female        3      3
61 1995      erin  7.22222         1      female        2      6
62 1995      opal  8.50000         1      female        3      9
63 1996    bertha  8.50000         1      female        2      8
64 1996      fran  7.16667         1      female        3     26
65 1997     danny  2.22222         0        male        1     10
66 1998    bonnie  9.38889         1      female        2      3
67 1998      earl  1.88889         0        male        1      3
68 1998   georges  2.27778         0        male        2      1
69 1999      bret  2.33333         0        male        3      0
70 1999     floyd  1.83333         0        male        2     56
71 1999     irene  9.27778         1      female        1      8
72 2002      lili 10.33333         1      female        1      2
73 2003 claudette  9.16667         1      female        1      3
74 2003    isabel  9.38889         1      female        2     51
75 2004      alex  4.16667         0        male        1      1
76 2004   charley  2.88889         0        male        4     10
77 2004   frances  6.00000         1      female        2      7
78 2004    gaston  2.66667         0        male        1      8
79 2004      ivan  1.05556         0        male        3     25
80 2004    jeanne  8.50000         1      female        3      5
81 2005     cindy  9.94444         1      female        1      1
82 2005    dennis  2.44444         0        male        3     15
83 2005   ophelia  9.16667         1      female        1      1
84 2005      rita  9.50000         1      female        3     62
85 2005     wilma  8.61111         1      female        3      5
86 2007  humberto  2.38889         0        male        1      1
87 2008     dolly  9.83333         1      female        1      1
88 2008    gustav  1.72222         0        male        2     52
89 2008       ike  1.88889         0        male        2     84
90 2011     irene  9.27778         1      female        1     41
91 2012     isaac  1.94444         0        male        1      5
92 2012     sandy  9.00000         1      female        2    159</code></pre>
</div>
</div>
<p>The <code>DT</code> (for datatable) package also includes some nice options (like a search bar and column sorting) for viewing data frames.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("DT")</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(hurricanes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div class="datatables html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-ecd6cfada14d624619e6" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-ecd6cfada14d624619e6">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92"],[1950,1950,1952,1953,1953,1954,1954,1954,1955,1955,1955,1956,1958,1959,1959,1960,1960,1961,1963,1964,1964,1964,1964,1965,1966,1966,1967,1968,1969,1970,1971,1971,1971,1972,1974,1975,1976,1977,1979,1979,1979,1980,1983,1984,1985,1985,1985,1985,1985,1985,1986,1986,1987,1988,1989,1989,1989,1991,1992,1993,1995,1995,1996,1996,1997,1998,1998,1998,1999,1999,1999,2002,2003,2003,2004,2004,2004,2004,2004,2004,2005,2005,2005,2005,2005,2007,2008,2008,2008,2011,2012,2012],["easy","king","able","barbara","florence","carol","edna","hazel","connie","diane","ione","flossy","helene","debra","gracie","donna","ethel","carla","cindy","cleo","dora","hilda","isbell","betsy","alma","inez","beulah","gladys","camille","celia","edith","fern","ginger","agnes","carmen","eloise","belle","babe","bob","david","frederic","allen","alicia","diana","bob","danny","elena","gloria","juan","kate","bonnie","charley","floyd","florence","chantal","hugo","jerry","bob","andrew","emily","erin","opal","bertha","fran","danny","bonnie","earl","georges","bret","floyd","irene","lili","claudette","isabel","alex","charley","frances","gaston","ivan","jeanne","cindy","dennis","ophelia","rita","wilma","humberto","dolly","gustav","ike","irene","isaac","sandy"],[6.77778,1.38889,3.83333,9.83333,8.33333,8.11111,8.55556,9.44444,8.5,9.88889,5.94444,7,9.88889,9.88889,9.77778,9.27778,8.72222,9.5,9.94444,7.94444,9.33333,8.83333,9.44444,8.33333,8.77778,8.27778,7.27778,8.94444,9.05556,9.44444,8.5,7.38889,10,8.66667,8.72222,8.94444,10.44445,6.88889,1.66667,1.72222,2.5,2.66667,9.83333,9.94444,1.66667,2.22222,9.72222,9.5,1.94444,9.66667,9.38889,2.88889,1.83333,8.33333,9.05556,2.88889,2.33333,1.66667,2.22222,9.83333,7.22222,8.5,8.5,7.16667,2.22222,9.38889,1.88889,2.27778,2.33333,1.83333,9.27778,10.33333,9.16667,9.38889,4.16667,2.88889,6,2.66667,1.05556,8.5,9.94444,2.44444,9.16667,9.5,8.61111,2.38889,9.83333,1.72222,1.88889,9.27778,1.94444,9],[1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1,1,0,0,1,1,0,1,1,0,0,1,1,0,0,0,0,1,1,1,1,1,0,1,0,0,0,0,1,1,1,1,0,0,1,0,0,1,1,0,1,1,1,0,1,0,0,1,0,1],["female","male","male","female","female","female","female","female","female","female","male","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","female","male","male","male","male","female","female","male","male","female","female","male","female","female","male","male","female","female","male","male","male","male","female","female","female","female","female","male","female","male","male","male","male","female","female","female","female","male","male","female","male","male","female","female","male","female","female","female","male","female","male","male","female","male","female"],[3,3,1,1,1,3,3,4,3,1,3,2,3,1,3,4,1,4,1,2,2,3,2,3,2,1,3,2,5,3,2,1,1,1,3,3,1,1,1,2,3,3,3,2,1,1,3,3,1,2,1,1,1,1,1,4,1,2,5,3,2,3,2,3,1,2,1,2,3,2,1,1,1,2,1,4,2,1,3,3,1,3,1,3,3,1,1,2,2,1,1,2],[2,4,3,1,0,60,20,20,0,200,7,15,1,0,22,50,0,46,3,3,5,37,3,75,6,3,15,3,256,22,0,2,0,117,1,21,5,0,1,15,5,2,21,3,0,1,4,8,12,5,3,5,0,1,13,21,3,15,62,3,6,9,8,26,10,3,3,1,0,56,8,2,3,51,1,10,7,8,25,5,1,15,1,62,5,1,1,52,84,41,5,159]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>year<\/th>\n      <th>name<\/th>\n      <th>masfem<\/th>\n      <th>gender_mf<\/th>\n      <th>male_female<\/th>\n      <th>category<\/th>\n      <th>deaths<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,3,4,6,7]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="types-of-variables" class="level2">
<h2 class="anchored" data-anchor-id="types-of-variables">Types of Variables</h2>
<p>We have different types of variables in our data frame. Some have the <code>int</code> tag identifying them as interval variables, some have the <code>Factor</code> tag identifying them as categorical variables, and some have the <code>numeric</code> tag.</p>
<p>Let’s look at the <code>name</code> variable to start. We can see in the <code>Environment</code> panel that this variable is a factor variable with 83 levels - or 83 different possible values. In this case, each value is a different name, making this an example of a <em>nominal variable</em>.</p>
<p>Why is this not an <em>ordinal variable</em>?</p>
<p>To see how many observations have each value - or how many hurricanes have each name - we will use the <code>table()</code> command. In R, we have to reference all variables by their data frame. So if we want a table of the <code>name</code> variable, we first have to tell R that the variable is in the <code>hurricanes</code> data frame. We separate the data frame and the variable name by a dollar sign:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(hurricanes<span class="sc">$</span>name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     able     agnes      alex    alicia     allen      alma    andrew      babe 
        1         1         1         1         1         1         1         1 
  barbara     belle    bertha     betsy    beulah       bob    bonnie      bret 
        1         1         1         1         1         3         2         1 
  camille     carla    carmen     carol     celia   chantal   charley     cindy 
        1         1         1         1         1         1         2         2 
claudette      cleo    connie     danny     david     debra    dennis     diana 
        1         1         1         2         1         1         1         1 
    diane     dolly     donna      dora      earl      easy     edith      edna 
        1         1         1         1         1         1         1         1 
    elena    eloise     emily      erin     ethel      fern  florence    flossy 
        1         1         1         1         1         1         2         1 
    floyd      fran   frances  frederic    gaston   georges    ginger    gladys 
        2         1         1         1         1         1         1         1 
   gloria    gracie    gustav     hazel    helene     hilda      hugo  humberto 
        1         1         1         1         1         1         1         1 
      ike      inez      ione     irene     isaac    isabel    isbell      ivan 
        1         1         1         2         1         1         1         1 
   jeanne     jerry      juan      kate      king      lili      opal   ophelia 
        1         1         1         1         1         1         1         1 
     rita     sandy     wilma 
        1         1         1 </code></pre>
</div>
</div>
<p>When you run that line of code you should see a table with every possible value of the <code>name</code> variable and the number of observations with that value. There is one hurricane named Able, for example. How many hurricanes are named Florence? Which hurricane name is most common?</p>
<p>By default, R will sort factor variables alphabetically. An easier way to see which factor has the most observations - in this case, which name has the most hurricanes - is to use the <code>sort()</code> function to order the names by the number of observations in each. Note that functions “wrap” code in parentheses:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(hurricanes<span class="sc">$</span>name))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     able     agnes      alex    alicia     allen      alma    andrew      babe 
        1         1         1         1         1         1         1         1 
  barbara     belle    bertha     betsy    beulah      bret   camille     carla 
        1         1         1         1         1         1         1         1 
   carmen     carol     celia   chantal claudette      cleo    connie     david 
        1         1         1         1         1         1         1         1 
    debra    dennis     diana     diane     dolly     donna      dora      earl 
        1         1         1         1         1         1         1         1 
     easy     edith      edna     elena    eloise     emily      erin     ethel 
        1         1         1         1         1         1         1         1 
     fern    flossy      fran   frances  frederic    gaston   georges    ginger 
        1         1         1         1         1         1         1         1 
   gladys    gloria    gracie    gustav     hazel    helene     hilda      hugo 
        1         1         1         1         1         1         1         1 
 humberto       ike      inez      ione     isaac    isabel    isbell      ivan 
        1         1         1         1         1         1         1         1 
   jeanne     jerry      juan      kate      king      lili      opal   ophelia 
        1         1         1         1         1         1         1         1 
     rita     sandy     wilma    bonnie   charley     cindy     danny  florence 
        1         1         1         2         2         2         2         2 
    floyd     irene       bob 
        2         2         3 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(hurricanes<span class="sc">$</span>name), <span class="at">decreasing=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      bob    bonnie   charley     cindy     danny  florence     floyd     irene 
        3         2         2         2         2         2         2         2 
     able     agnes      alex    alicia     allen      alma    andrew      babe 
        1         1         1         1         1         1         1         1 
  barbara     belle    bertha     betsy    beulah      bret   camille     carla 
        1         1         1         1         1         1         1         1 
   carmen     carol     celia   chantal claudette      cleo    connie     david 
        1         1         1         1         1         1         1         1 
    debra    dennis     diana     diane     dolly     donna      dora      earl 
        1         1         1         1         1         1         1         1 
     easy     edith      edna     elena    eloise     emily      erin     ethel 
        1         1         1         1         1         1         1         1 
     fern    flossy      fran   frances  frederic    gaston   georges    ginger 
        1         1         1         1         1         1         1         1 
   gladys    gloria    gracie    gustav     hazel    helene     hilda      hugo 
        1         1         1         1         1         1         1         1 
 humberto       ike      inez      ione     isaac    isabel    isbell      ivan 
        1         1         1         1         1         1         1         1 
   jeanne     jerry      juan      kate      king      lili      opal   ophelia 
        1         1         1         1         1         1         1         1 
     rita     sandy     wilma 
        1         1         1 </code></pre>
</div>
</div>
<p>Now let’s look at another categorical factor variable - <code>male_female</code> - which identifies whether a hurricane has a male or female name. Try making a table of this variable to see how many hurricanes have male and female names.</p>
<section id="replace-this-line-with-your-code-1" class="level3">
<h3 class="anchored" data-anchor-id="replace-this-line-with-your-code-1">REPLACE THIS LINE WITH YOUR CODE</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(hurricanes<span class="sc">$</span>male_female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
female   male 
    62     30 </code></pre>
</div>
</div>
<p>R calls the <code>male_female</code> variable a factor variable because its values are text categories rather than numbers. The <code>gender_mf</code> variable is a numerical variable that has the same exact information as the <code>male_female</code> variable but uses a 0 to indicate a hurricane with a male name and a 1 to indicate a hurricane with a female name. A variable that takes the values 0 and 1 is called a <em>binary variable</em>.</p>
<p>We can use the <code>table()</code> function with binary and interval variables as well. But it can also be helpful to use the <code>summary()</code> function when we have numerical data. For example, execute the following code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hurricanes<span class="sc">$</span>gender_mf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  1.0000  0.6739  1.0000  1.0000 </code></pre>
</div>
</div>
<p>The minimum and maximum values of a binary variable will always be 0 and 1. The mean of a binary variable is the proportion with a 1. <em>[Remember this…it will be a trick that will save you lots of time in future weeks!].</em> So the mean of <code>gender_mf</code> tells us that 67.39% of the hurricanes in this sample have female names (or have a value of 1 for the <code>gender_mf</code> variable).</p>
<p>How could you use R as a calculator to see that 67.39% of the hurricanes in this sample have female names?</p>
</section>
<section id="replace-this-line-with-your-code-2" class="level3">
<h3 class="anchored" data-anchor-id="replace-this-line-with-your-code-2">REPLACE THIS LINE WITH YOUR CODE</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="dv">62</span><span class="sc">/</span><span class="dv">92</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.673913</code></pre>
</div>
</div>
<p>The summary() command is more helpful when numerical variables have many possible values because we get a snapshot of the distribution of values. Let’s look at the <code>deaths</code> variable, which is the number of deaths per hurricane. This is an example of a <em>discrete variable</em> since its values jump between whole numbers. It is not a <em>continuous variable</em> because the values are whole numbers; for example, there are either 2 or 3 deaths, not 2.4 or 2.8.</p>
<p>What is an example of a <em>continuous variable</em> in this data frame?</p>
<p>Try summarizing the <code>deaths</code> variable to find the mean (or average) number of hurricane-related deaths in this sample:</p>
</section>
<section id="replace-this-line-with-your-code-3" class="level3">
<h3 class="anchored" data-anchor-id="replace-this-line-with-your-code-3">REPLACE THIS LINE WITH YOUR CODE</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hurricanes<span class="sc">$</span>deaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    2.00    5.00   20.65   20.25  256.00 </code></pre>
</div>
</div>
<p>How could we find the hurricane with 256 deaths? Sometimes we only want to use a function for some observations rather than all observations. <code>R</code> calls this <em>indexing</em>. We use brackets to indicate the variable names and values we want to index.</p>
<p>In this next chunk, we want to pull the value for the <code>name</code> variable for the observation where the value for the <code>deaths</code> variable equals 256. Note that in R we will use two equal signs when referencing a specific value that exists in a data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>hurricanes<span class="sc">$</span>name[hurricanes<span class="sc">$</span>deaths<span class="sc">==</span><span class="dv">256</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] camille
83 Levels: able agnes alex alicia allen alma andrew babe barbara ... wilma</code></pre>
</div>
</div>
<p>Other indexing tools that are helpful:</p>
<ul>
<li>For greater than, use &gt;</li>
<li>For less than, use &lt;</li>
<li>For greater than or equal to, use &gt;=</li>
<li>For less than or equal to, use &lt;=</li>
<li>For not equal to, use !=</li>
</ul>
<p>Finally, let’s combine indexing with <code>summary()</code> to find how mean number of deaths varies by the gender of a hurricane’s name.</p>
<p>Here’s the code for hurricanes with male names:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hurricanes<span class="sc">$</span>deaths[hurricanes<span class="sc">$</span>male_female<span class="sc">==</span><span class="st">"male"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    1.25    5.00   14.23   15.00   84.00 </code></pre>
</div>
</div>
<p>Repeat the summary of the <code>deaths</code> variable for hurricanes with female names:</p>
</section>
<section id="replace-this-line-with-your-code-4" class="level3">
<h3 class="anchored" data-anchor-id="replace-this-line-with-your-code-4">REPLACE THIS LINE WITH YOUR CODE</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hurricanes<span class="sc">$</span>deaths[hurricanes<span class="sc">$</span>male_female<span class="sc">==</span><span class="st">"female"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    2.00    5.00   23.76   21.00  256.00 </code></pre>
</div>
</div>
<p>Eventually we will simplify to something like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>hurricanes <span class="sc">|&gt;</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(male_female) <span class="sc">|&gt;</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(deaths))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  male_female  mean
  &lt;fct&gt;       &lt;dbl&gt;
1 female       23.8
2 male         14.2</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>hurricanes <span class="sc">|&gt;</span>  <span class="fu">group_by</span>(male_female) <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">summarise</span>(<span class="at">deaths_mean =</span> <span class="fu">round</span>(<span class="fu">mean</span>(deaths),<span class="dv">2</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> male_female, <span class="at">y =</span> deaths_mean, <span class="at">fill =</span> male_female)) <span class="sc">+</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span> </span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> deaths_mean), <span class="at">size =</span> <span class="dv">6</span>, <span class="at">vjust =</span> <span class="dv">0</span>) <span class="sc">+</span> </span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Mean Number of Deaths"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Mean Number of Deaths by Gender of Hurricane Name"</span>) <span class="sc">+</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_hc</span>() <span class="sc">+</span> <span class="fu">scale_fill_economist</span>(<span class="at">name =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">25</span>)) <span class="sc">+</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">18</span>),</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">18</span>),</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)) <span class="sc">+</span> <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="notebook_01_02_ml_files/figure-html/plot%20example%202-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>