---
geometry: margin=1.0in
fontsize: 12pt
output: 
  pdf_document:
    highlight: espresso
header-includes:
      \usepackage{nopageno}
---

## SOCI 485 - Fall 2023
## Software Setup (PC/Windows Version)

**1) Download and Install `R`**

`R` is available as a free download at [`this site`](https://cran.r-project.org). If your system software is up to date you should download version 4.3.1 for Windows. After choosing the base version of `R` you want, click to install and follow the on-screen instructions. You may have to double click on the downloaded package to start the process; that package should be in the folder where you saved the file.

To test if the installation was successful, open `R` and type `summary(cars)` on the command line and press enter. You should see the summary of the `speed` and `dist` variables from the built-in `cars` dataset.

**2) Install `tinytex`**

`R` uses LaTeX to produce pdf documents from `Quarto` files. To install the parts of LaTeX that we will need, type the following into the `R` console and then press enter:

```{r eval = FALSE}
install.packages('tinytex')
tinytex::install_tinytex()
```

The package will download to your library and may also install additional necessary packages. The console arrow will reappear when the installations are complete.

**3) Download and Install `R Studio`**

`R Studio` is available as a free download at [`this site`](https://www.rstudio.com/products/rstudio/download/). Scroll down to find the installer for the free RStudio Desktop version. Click the download button. The package will start downloading. When it finishes doing so, double click on the downloaded file and follow the installation instructions.

To test if the installation was successful, open `R Studio` - not `R` - and type `summary(cars)` on the command line in the `Console` quadrant (the bottom left panel). When you press enter you should see the same summary of the `speed` and `dist` variables from the built-in `cars` dataset.

**4) Test `R Markdown`**

You can test if `tinytex` was installed correctly by opening `R Studio` again. Click the `File` menu bar, scroll down to `New File`, and select `Quarto Document`. If a message appears suggesting you install additional packages, do so. Enter your "Setting Up R" in the `Title` field, you name in the `Author` field, select "HTML" as the output format, and then click `Create`. A default template should open in the top left panel of `R Studio`.

Now let's see if everything is working properly. Save this file in a folder where you want to save your work for this class. Then click the `Render` button on the toolbar just above where the title of your document has been inserted. If everything installed correctly and is working well, you should have just created a HTML document in your working directory.